springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
spring:
  security:
    user:
      name: root
      password: root
  profiles:
    active: mysql
  sql:
    init:
      mode: always
  application:
    name: Streaming Service
  cloud:
    gcp:
      sql:
        database-name: streaming_service
        instance-connection-name: digital-splicer-420721:europe-west1:steaming-service
  datasource:
    username: root
    password: zxc1596
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
      file-size-threshold: 2KB
server:
  port: 8080
api:
  stripe:
    key: sk_test_51MjSvlFARn3daPh2BZK5w2CdwkxDqUcUzgoHW6WYFYCo227NlUr7tQuamhdGkrvHdTmJkS3vqKlfjqRyFciHf0a200l9ciSAhM
jwt:
  secret-key: b26abf5db60ed7128830420838e03dbf6b729d74143d1e0a1dfa268d339f781a