springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DMAIL_USERNAME}
    password: ${DMAIL_PASSWORD}
    from: ${DMAIL_FROM}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    user:
      name: root
      password: root
  sql:
    init:
      mode: always
  application:
    name: Streaming Service
  cloud:
    gcp:
      sql:
        database-name: streaming_service
        instance-connection-name: digital-splicer-420721:europe-west1:steaming-service
  datasource:
    username: ${DDATASOURCE_USER}
    password: ${DDATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
      file-size-threshold: 2KB
server:
  port: 8080
jwt:
  secret-key: b26abf5db60ed7128830420838e03dbf6b729d74143d1e0a1dfa268d339f781a
api:
  stripe:
    key: ${DSTRIPE_KEY}